package twitchpokedex.database.maps;

// Generated 08/01/2015 2:48:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pokemon generated by hbm2java
 */
public class Pokemon implements java.io.Serializable
{

	private int id;
	private String name;
	private Set userses = new HashSet(0);

	public Pokemon()
	{
	}

	public Pokemon(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Pokemon(int id, String name, Set userses)
	{
		this.id = id;
		this.name = name;
		this.userses = userses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set getUserses()
	{
		return this.userses;
	}

	public void setUserses(Set userses)
	{
		this.userses = userses;
	}

}
