package twitchpokedex.database.maps;

// Generated 08/01/2015 2:48:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Settings generated by hbm2java
 */
public class Setting implements java.io.Serializable
{

	private String key;
	private String value;

	public Setting()
	{
	}

	public Setting(String key, String value)
	{
		this.key = key;
		this.value = value;
	}

	public String getKey()
	{
		return this.key;
	}

	public void setKey(String key)
	{
		this.key = key;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

}
