package twitchpokedex.database.maps;

// Generated 08/01/2015 2:48:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import twitchpokedex.database.DBConn;

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable
{
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	private int twitchId;
	private String username;
	private String displayName;
	private int points;
	private int donator;
	private Date updatedAt;

	public User()
	{
	}

	public User(int twitchId, String username,
			String displayName, int points, int donator, Date updatedAt)
	{
		this.twitchId = twitchId;
		this.username = username;
		this.displayName = displayName;
		this.points = points;
		this.donator = donator;
		this.updatedAt = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public int getTwitchId()
	{
		return this.twitchId;
	}

	public void setTwitchId(int twitchId)
	{
		this.twitchId = twitchId;
	}

	public String getUsername()
	{
		return this.username;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public String getDisplayName()
	{
		return this.displayName;
	}

	public void setDisplayName(String displayName)
	{
		this.displayName = displayName;
	}

	public int getPoints()
	{
		return this.points;
	}

	public void setPoints(int points)
	{
		this.points = points;
	}
	
	public void addPoints(int points)
	{
		this.points += points;
	}

	public int getDonator()
	{
		return this.donator;
	}

	public void setDonator(int donator)
	{
		this.donator = donator;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public boolean isDefault()
	{
		return this.id == 0;
	}
	
	public void Save()
	{
		DBConn.UpdateUser(this);
	}
}
